### ISSUE TITLE
Revoir la page A propos

### ISSUE THREAD

**Issue by syji35** [megalis-bretagne/lufi-docker#12]
Revoir la page à Propos

**Comment by FlorianChatel** [comment]
**Qu’est-ce que Transfert de fichiers ?** 
Transfert de fichier est un service disponible avec le Bouquet Mégalis Bretagne 2025-2029. Il est accessible pour tous les utilisateurs disposant d’un compte Mégalis. 

**Confidentialité**
Tous Les fichiers déposés sur Transfert de Fichiers sont chiffrés avant l’envoi au serveur. Mégalis Bretagne ne peut pas voir le contenu de vos documents. Seulement le nom du fichier, sa taille et son type (texte, vidéo, son…). 
Vous n’avez pas besoin de vous enregistrer pour envoyer des fichiers mais notez que, pour des raisons légales, votre adresse IP sera enregistrée quand vous envoyez un fichier. 

**Comment ça marche ?** 
Faites un "glisser/déposer" de vos fichiers dans la zone prévue à cet effet ou téléversez un fichier en le sélectionnant depuis votre navigateur de fichier.
Une fois, cette manipulation effectuée, vous récupérerez deux liens par fichier : un lien de téléchargement et un lien pour supprimer le fichier quand vous le souhaitez.

Vous pouvez voir la liste de vos fichiers en cliquant sur le lien « Mes fichiers » en haut à droite de cette page. 
Vous avez accès à un espace de stockage de 2 Go maximum et les fichiers sont effacés au bout de 7 jours par défaut.

Si besoin, n’hésitez pas à consulter les tutoriels sur le site de Mégalis Bretagne : https://services.megalis.bretagne.bzh/tutoriels/

**Comment signaler un problème ?**
Mégalis Bretagne met à la disposition des usagers une [assistance des services numérique](https://services.megalis.bretagne.bzh/assistance/). Vous pouvez la contacter si vous avez une question ou si vous souhaiter un accompagnement sur Transfert de Fichiers. Vous pouvez également envoyer un [formulaire](https://services.megalis.bretagne.bzh/formulaire-de-contact-collectivites/) si vous avez besoin de plus d’information. 

**Version**

0.7.0
