### ISSUE TITLE
Behind HTTPS proxy

### ISSUE THREAD

**Issue by borekon** [megalis-bretagne/lufi-docker#6]
![image](https://github.com/megalis-bretagne/lufi-docker/assets/9289539/bbc0b020-ee80-4ee7-ad55-63949afe59a8)
The upload is not working because i'm accesing main page with https (nginx proxy manager) and the page loads in HTTPS but tries to open a non-secured websocket _ws://_ instead of _wss://_

**Comment by syji35** [comment]
Hi,


It depends on your configuration with Apache or Nginx. You also need to enable the Hypnotoad configuration with the proxy set to 1.

https://framagit.org/fiat-tux/hat-softwares/lufi/-/blob/master/lufi.conf.template?ref_type=heads#L13

**Comment by borekon** [comment]
Thanks! Just uncommenting the proxy section did the trick :)
