### ISSUE TITLE
Little oops in Dockerfile regarding config file, preventing application to start

### ISSUE THREAD

**Issue by seboss666** [megalis-bretagne/lufi-docker#7]
Hello,

First of all, thank you for this project that ease the process of deploying this pleasant project in container environments 😄 

I won't create a pull request for a one-liner, just to mention that there is what I consider a typo in the Dockerfile, that will prevent the application to start correctly (it happened to me during a live stream on Twitch ^^'). At this line: https://github.com/megalis-bretagne/lufi-docker/blob/58189ee795199c13ba3013a0823c7e89612c47d6/Dockerfile#L44

The config file destination should be in the workdir instead of the root of the image filesystem. So the line should be:
```Dockerfile
COPY --chown=nonroot:nonroot lufi.conf .
```
Notice the dot instead of the slash at the end (as the workdir is defined a few lines earlier). I let you commit this quick little fix 😉

**Comment by syji35** [comment]
Hi @seboss666 

Thank you for the feedback. I have just made the fix: https://github.com/megalis-bretagne/lufi-docker/pull/8

Thanks.
